#docker-compose -f docker-compose.yml up -d
version: '3.7'

services:
  file-server:
    image: node:16-alpine3.14
    container_name: file_server
    ports:
      - 9040:9040
    expose:
      - 9040
    working_dir: /app
    volumes:
      # update path as per your directory structure
      - $HOME/uzrnem/node-file-server:/app
    command: sh -c "npm install && npm run start"